### PR TITLE
[TA2546] feat(snaprebuild) IOs on the cloned volume if it exists

### PR DESCRIPTION
**Pull request by pawanpraka1**
All the read/write/sync IOs should go to clone volume since it will
be active file system(AFS) at the time of rebuilding.

Signed-off-by: Pawan <pawanprakash101@gmail.com>

### CODE REVIEW

**Review by vishnuitta — COMMENTED** [review]
Write IOs doesn’t seem to be handled.

**Review by satbirchhikara — APPROVED** [review]
LGMT

**Comment by pawanpraka1** [comment]
@vishnuitta, writes are already handled in uzfs_submit_writes.

**Comment by pawanpraka1** [comment]
closing this as we have handled it in https://github.com/openebs/zfs/pull/123.

**Pull request closed without merging**
