### PR TITLE
Update README.markdown

### PR DESCRIPTION
**Pull request by hflamboauto1**

### CODE REVIEW

**Review by pawanpraka1 — APPROVED** [review]
looks good.

**Comment by pawanpraka1** [comment]
can you DCO sign off this commit?
```
Sign your work
We use the Developer Certificate of Origin (DCO) as an additional safeguard for the OpenEBS project. This is a well established and widely used mechanism to assure that contributors have confirmed their right to license their contribution under the project's license. Please read dcofile. If you can certify it, then just add a line to every git commit message:

  Signed-off-by: Random J Developer <random@developer.example.org>
Use your real name (sorry, no pseudonyms or anonymous contributions). The email id should match the email id provided in your GitHub profile. If you set your user.name and user.email in git config, you can sign your commit automatically with git commit -s.

You can also use git aliases like git config --global alias.ci 'commit -s'. Now you can commit with git ci and the commit will be signed.
```

**Comment by hflamboauto1** [comment]
> can you DCO sign off this commit?
> 
> ```
> Sign your work
> We use the Developer Certificate of Origin (DCO) as an additional safeguard for the OpenEBS project. This is a well established and widely used mechanism to assure that contributors have confirmed their right to license their contribution under the project's license. Please read dcofile. If you can certify it, then just add a line to every git commit message:
> 
>   Signed-off-by: Random J Developer <random@developer.example.org>
> Use your real name (sorry, no pseudonyms or anonymous contributions). The email id should match the email id provided in your GitHub profile. If you set your user.name and user.email in git config, you can sign your commit automatically with git commit -s.
> 
> You can also use git aliases like git config --global alias.ci 'commit -s'. Now you can commit with git ci and the commit will be signed.
> ```

Sure will do. Good to learn about this as well. Thank you.

**Comment by hflamboauto1** [comment]
closing in favor of #273

**Pull request closed without merging**
