### PR TITLE
Reverting logging changes

### LINKED ISSUE #2762: Revert changes done in cstor as part of new error logging format
## Description

With this PR https://github.com/openebs/cstor/pull/266, lot of changes related to new error logging format has been added.
`cstor` repo deviating too much from upstream will make it difficult to keep cstor repo in sync with upstream.
This issue is created to remove the changed related to above mentioned PR.
New error logging format is handled at ZFS/ZPOOL client used in `maya` repo.

## Your Environment

* `kubectl get nodes`:
* `kubectl get pods --all-namespaces`:
* `kubectl get services`:
* `kubectl get sc`:
* `kubectl get pv`:
* `kubectl get pvc`:
* OS (from `/etc/os-release`):
* Kernel (from `uname -a`):
* Install tools:
* Others:

### PR DESCRIPTION
**Pull request by NaveenBellary**
Signed-off-by: Naveen Bellary <<bellary.naveen@gmail.com>>

What this PR does / why we need it: This PR reverts logging changes made as part of https://github.com/openebs/cstor/commit/d481a92c8b855984b2e1f9ee2ea9e4d6a190beb3

Which issue this PR fixes : https://github.com/openebs/openebs/issues/2762

### CODE REVIEW

**Comment by NaveenBellary** [comment]
Instead of removing the changes and reverting the code, I've removed the commit, https://github.com/openebs/cstor/commit/d481a92c8b855984b2e1f9ee2ea9e4d6a190beb3 and rebased the branch using the below command:

`git rebase -i d481a92c8~1`

@vishnuitta -- Let me know if that'll suffice

**Comment by pawanpraka1** [comment]
you should use `git revert <commit hash>` to revert the desired commit and raise the PR with that.

**Comment by NaveenBellary** [comment]
@pawanpraka1, wouldn't `git revert` change the `head` to the `<commit hash>`? Also, even though the diff of this pull request is showing the three commits after https://github.com/openebs/cstor/commit/d481a92c8b855984b2e1f9ee2ea9e4d6a190beb3, when  you do a `git diff develop` with this branch, the changes are only of the reversal from the desired commit.
Let me know if that's not the case.

**Comment by pawanpraka1** [comment]
no, `git revert <commit hash>` will create a new commit which will revert the desired commit. What you did in you PR is remoed that commit on your forked repo. You can not make a commit disappear. You should have a commit which reverts the desired commit on top of head.

**Comment by NaveenBellary** [comment]
Got it. Thanks for the explanation @pawanpraka1.

**Comment by NaveenBellary** [comment]
@vishnuitta, @pawanpraka1 -- I've created a new PR for the changes. https://github.com/openebs/cstor/pull/274

Closing this one

**Pull request closed without merging**
